output: ../results/gt/lcao.h5
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.0001
ode_builder:
  class_path: src.ode.LCAO
  init_args:
    lin_coeff: 1.0
    cubic_coeff: 2.0
    coupling_coeff: 0.5
x0: '[[1.0, -2.0], [-1.0, 0.5]]'
t0: 0.0
tN: 80.0
noise_var: 0.0
save_interval: 100
disable_pbar: false
