output: ../results/gt/lorenz.h5
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.0001
ode_builder:
  class_path: src.ode.Lorenz
x0: '[[1.0, 1.0, 1.0]]'
t0: 0.0
tN: 50.0
noise_var: 0.0
save_interval: 10
disable_pbar: false
