output: ../results/gt/rlc.h5
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.0001
ode_builder:
  class_path: src.ode.RLCCircuit
  init_args:
    resistance: 100
    inductance: 250
    capacitance: 3.5E-05
x0: '[[10.0], [0.0]]'
t0: 0.0
tN: 10.0
noise_var: 0.0
save_interval: 10
disable_pbar: false