output: ../results/params_baseline/lotkavolterra2.h5
solver_builder: 
  class_path: src.solvers.RKF45
  init_args:
    step_size: 0.01
ode_builder:
  class_path: src.ode.LotkaVolterra
  init_args:
    alpha: 1.5
    beta: 1.0
    gamma: 3.0
    delta: 1.0
x0: '[[1.0, 1.0]]'
t0: 0.0
tN: 20.0
y_path: ../results/noise_gt/lotkavolterra.h5
measurement_matrix: '[[1, 0]]'
params_range: 
  alpha: [0.001, 5.0]
  beta: [0.001, 5.0]
  gamma: [0.001, 5.0]
  delta: [0.001, 5.0]
params_optimized:
  alpha: true
  beta: true
  gamma: false
  delta: false
obs_noise_var: 0.1
lbfgs_maxiter: 200
initial_state_parametrized: false
num_random_runs: 100
num_param_evals:
  alpha: 50
  beta: 50
  gamma: 1
  delta: 1
seed: 2
num_processes: 4
disable_pbar: false
verbose: false