output: ../results/params/pendulum.h5
filter_builder:
  class_path: src.filters.SQRT_EKF
  init_args:
    cov_update_fn_builder:
      class_path: src.covariance_update_functions.DiagonalCovarianceUpdate
      init_args:
        scale: 1.0
    disable_cov_update: true
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.01
ode_builder:
  class_path: src.ode.Pendulum
  init_args:
    length: 1.5
x0: '[[0.785398], [0.0]]'
P0: null
t0: 0.0
tN: 10.0
y_path: ../results/noise_gt/pendulum.h5
measurement_matrix: '[[1, 0]]'
params_range:
  length: [0.1, 10.0]
params_optimized:
  length: true
num_tempering_steps: 4
obs_noise_var: 0.1
gamma_noise_schedule:
  class_path: src.noise_schedules.CosineAnnealingSchedule
  init_args:
    init_noise_log: -3.2
    min_noise_log: -8.0
    cycle_length: 2
lbfgs_maxiter: 200
num_random_runs: 100
num_param_evals:
  length: 1000
seed: 7
num_processes: 4
disable_pbar: false
verbose: false