output: ../results/noise_gt/hodgkinhuxley_r4.h5
solver_builder: 
  class_path: src.solvers.DiffraxSolverBuilder
  init_args:
    name: Kvaerno3
    step_size: 0.0001
ode_builder:
  class_path: src.ode.HodgkinHuxley
  init_args:
    model: reduced-4
    C: 1.0
    A: 8.3e-05
    g_Na: 25.0
    E_Na: 53.0
    g_K: 7.0
    E_K: -107.0
    g_leak: 0.1
    E_leak: -70.0
    V_T: -60.0
    g_M: 0.01
    tau_max: 4000.0
    g_L: 0.01
    E_Ca: 120.0
    g_T: 0.0
    V_x: 2.0
x0: '[[-70.0]]'
t0: 0.0
tN: 100.0
noise_var: 0.1
save_interval: 100
disable_pbar: false
