output: null
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.0001
ode_builder:
  class_path: src.ode.Pendulum
  init_args:
    length: 3.0
x0: '[[0.785398], [0.0]]'
t0: 0.0
tN: 10.0
noise_var: 0.1
save_interval: 100
disable_pbar: false
