output: ../results/noise_gt/vanderpol.h5
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.0001
ode_builder:
  class_path: src.ode.VanDerPol
  init_args:
    damping: 5.0
x0: '[[2.0], [10.0]]'
t0: 10.0
tN: 80.0
noise_var: 0.1
save_interval: 100
disable_pbar: false
