output: ../results/conrad_baseline/rkf45/vanderpol.h5
filter_builder:
  class_path: src.filters.SQRT_EKF
  init_args:
    cov_update_fn_builder:
      class_path: src.covariance_update_functions.DiagonalCovarianceUpdate
      init_args:
        scale: 1.0
    static_cov_update_fn_builder:
      class_path: src.covariance_update_functions.StaticDiagonalCovarianceUpdate
      init_args:
        scale: 1.0
solver_builder: 
  class_path: src.solvers.RKF45
  init_args:
    step_size: 0.01
ode_builder:
  class_path: src.ode.VanDerPol
  init_args:
    damping: 5.0
x0: '[[2.0], [10.0]]'
P0: null
t0: 10.0
tN: 80.0
y_path: ../results/gt/vanderpol.h5
measurement_matrix: '[[1, 0], [0, 1]]'
obs_noise_var: 0.0
min_noise_log: -16.0
max_noise_log: 0.0
num_noise_levels: 500
disable_pbar: false
