output: null
filter_builder:
  class_path: src.filters.SQRT_EKF
  init_args:
    cov_update_fn_builder:
      class_path: src.covariance_update_functions.OuterCovarianceUpdate
      init_args:
        scale: 0.3
solver_builder: 
  class_path: src.solvers.BS32
  init_args:
    step_size: 0.1
ode_builder:
  class_path: src.ode.RLCCircuit
  init_args:
    resistance: 100
    inductance: 250
    capacitance: 3.5E-05
x0: '[[10.0], [0.0]]'
P0: null
t0: 0.0
tN: 10.0
y_path: null #../results/noise_gt/exp.h5
measurement_matrix: '[[1, 0],[0, 1]]'
obs_noise_var: 0.1
save_interval: 1
disable_pbar: false
