output: null
filter_builder:
  class_path: src.filters.SQRT_EKF
  init_args:
    cov_update_fn_builder:
      class_path: src.covariance_update_functions.DiagonalCovarianceUpdate
      init_args:
        scale: 3.0
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.01
ode_builder:
  class_path: src.ode.LCAO
  init_args:
    lin_coeff: 1.0
    cubic_coeff: 2.0
    coupling_coeff: 0.5
x0: '[[1.0, -2.0], [-1.0, 0.5]]'
P0: null
t0: 0.0
tN: 80.0
y_path: ../results/gt/lcao.h5
measurement_matrix: '[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]'
obs_noise_var: 0.0
save_interval: 1
disable_pbar: false
