output: ../results/params_plus/hodgkinhuxley6_c2_r1.h5
filter_builder:
  class_path: src.filters.SQRT_EKF
  init_args:
    cov_update_fn_builder:
      class_path: src.covariance_update_functions.DiagonalCovarianceUpdate
      init_args:
        scale: 1.0
    disable_cov_update: true
solver_builder: 
  class_path: src.solvers.DiffraxSolverBuilder
  init_args:
    name: Kvaerno3
    step_size: 0.01
ode_builder:
  class_path: src.ode.MultiCompartmentHodgkinHuxley
  init_args:
    model: reduced-1
    num_compartments: 2
    coupling_coeffs: '[1.0]'
    C: 1.0
    A: '[4.15e-5, 4.15e-5]'
    g_Na: '[25.0, 20.0]'
    E_Na: '[53.0, 53.0]'
    g_K: '[7.0, 10.0]'
    E_K: '[-107.0, -107.0]'
    g_leak: '[0.09, 0.11]'
    E_leak: '[-70.0, -70.0]'
    V_T: '[-70.0, -50.0]'
    g_M: '[0.01, 0.1]'
    tau_max: '[4e3, 4e3]'
    g_L: '[0.1, 0.01]'
    E_Ca: '[120.0, 120.0]'
    g_T: '[0.0, 0.0]'
    V_x: '[2.0, 2.0]'
x0: '[[-70.0, -70.0]]'
P0: null
t0: 0.0
tN: 100.0
y_path: ../results/noise_gt/hodgkinhuxley_c2_r1.h5
measurement_matrix: '[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]]'
params_range:
  coupling_coeffs: [1.0, 1.0]
  C: [0.4, 3.0]
  A: [1.9e-05, 30.2e-05]
  g_Na: [0.5, 80.0]
  E_Na: [50.0, 100.0]
  g_K: [1.0e-04, 15.0]
  E_K: [-110.0, -70.0]
  g_leak: [1.0e-04, 0.6]
  E_leak: [-100.0, -35.0]
  V_T: [-90.0, -40.0]
  g_M: [1.0e-04, 0.6]
  tau_max: [50.0, 5000.0]  # 3000.0 lower than obs=4000.0 (?)
  g_L: [-1.0e-04, 0.6]
  E_Ca: [100.0, 150.0]
  g_T: [-1.0e-04, 0.6]
  V_x: [0.0, 4.0]
params_optimized:
  coupling_coeffs: false
  C: false
  A: false
  g_Na: true
  E_Na: false
  g_K: true
  E_K: false
  g_leak: true
  E_leak: false
  V_T: true
  g_M: true
  tau_max: false
  g_L: true
  E_Ca: false
  g_T: false
  V_x: false
num_tempering_stages: 4
final_gamma_zero: true
obs_noise_var: 0.1
gamma_noise_schedule:
  class_path: src.noise_schedules.LinearDecaySchedule
  init_args:
    init_noise_log: -2.0
    decay_rate: 3
gamma_noise_weights: '[1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0]'
initial_state_parametrized: false
parameter_sensitivity: false
lbfgs_maxiter: 400
num_random_runs: 100
num_param_evals:
  coupling_coeffs: 1
  C: 100
  A: 1
  g_Na: 1
  E_Na: 1
  g_K: 1
  E_K: 1
  g_leak: 1
  E_leak: 1
  V_T: 1
  g_M: 1
  tau_max: 1
  g_L: 1
  E_Ca: 1
  g_T: 1
  V_x: 1
seed: 621
num_processes: 4
disable_pbar: false
verbose: false
