output: null
filter_builder:
  class_path: src.filters.ParticleFilter
  init_args:
    num_particles: 100
    cov_fn_builder:
      class_path: src.covariance_functions.OuterCovariance
      init_args:
        scale: 1.0
solver_builder: 
  class_path: src.solvers.Dopri65
  init_args:
    step_size: 0.01
ode_builder:
  class_path: src.ode.VanDerPol
  init_args:
    damping: 5.0
x0: '[[2.0], [10.0]]'
P0: null
t0: 10.0
tN: 80.0
y_path: null #../results/gt/vanderpol.h5
measurement_matrix: '[[1, 0], [0, 1]]'
obs_noise_var: 0.0
save_interval: 1
disable_pbar: false
